#!/bin/sh

# ping all nodes to check interfaces are set up correctly
ok=true
while read what type number hwaddr ipv4 ipv6
do
    [ "$what" = ADDR ] || continue
    ping -c1 -n -W1 "$ipv6" >/dev/null 2>&1 && continue
    echo "Fail: $type$number"
    ok=false
done < /tmp/experiment/setup-data

$ok && exit 0
echo "Some nodes could not be reached"
exit 1

