#!/bin/bash

# "random" client schedule: sleep a random time between 0 and the
# duration of the "immediate" experiment
delay=$(( $RANDOM % ( $duration + 1 ) ))
echo "Schedule delay: $delay / $duration" >> "$logfile"
sleep $delay

