#!/bin/sh

# start the experiment

schedule="$1"
experiment="$2"
type="$3"
number="$4"
size="$5"

# setup-node writes the name of the interface to use for packets here
interface="`head -1 /tmp/interface`"

# select a random server IPv6 address, if the experiment requires it
server="` \
    awk '/^ADDR server/ { print $NF }' /tmp/experiment/setup-data | \
    shuf | \
    head -1`"

# run any preparation which we do not want to measure; we only run the
# first one we find, but if that needs to include a more generic one it
# can do that
if [ -x "/tmp/experiment/prepare-$experiment-$type" ]
then
    "/tmp/experiment/prepare-$experiment-$type" "$server" "$interface"
elif [ -x "/tmp/experiment/prepare-$experiment" ]
then
    "/tmp/experiment/prepare-$experiment" "$server" "$interface"
elif [ -x "/tmp/experiment/prepare-$type" ]
then
    "/tmp/experiment/prepare-$type" "$server" "$interface"
elif [ -x "/tmp/experiment/prepare" ]
then
    "/tmp/experiment/prepare" "$server" "$interface"
fi

# run the scheduler for clients only
if [ "$type" = client ]
then
    "/tmp/experiment/schedule-$schedule"
    # make sure we don't find a permission problem because some experiments
    # run as root, and some don't
    sudo rm -f /tmp/datafile
fi

sed -e 's/\[TYPE\]/'"$type"'/g' \
    -e 's/\[NODE\]/'"$number"'/g' \
    -e 's/\[EXPERIMENT\]/'"$experiment"'/g' \
    -e 's/\[INTERFACE\]/'"$interface"'/g' \
    -e 's/\[SERVER\]/'"$server"'/g' \
    -e 's/\[SCHEDULE\]/'"$schedule"'/g' \
    -e 's/\[SIZE\]/'"$size"'/g' \
    /tmp/experiment/lwmon-config > /tmp/lwmon-config

ifnum=0
while read ifname
do
    ifnum=$(( 1 + $ifnum ))
    echo "network if$ifnum 1 $ifname" >> /tmp/lwmon-config
done < /tmp/interface

rm -r /tmp/results >/dev/null 2>&1
mkdir /tmp/results
lwmon -c /tmp/lwmon-config

# copy the results back to director
director="`awk '/^ADDR director/ { print $NF; exit }' /tmp/experiment/setup-data`"
scp -oCheckHostIP=no -oStrictHostKeyChecking=no -i/tmp/experiment/id_rsa \
    /tmp/results/* "[$director]:/tmp/results/"
rm -r /tmp/results >/dev/null 2>&1

