#!/bin/sh

# start the experiment

export schedule="$1"
export experiment="$2"
export type="$3"
export number="$4"
export size="$5"

# setup-node writes the name of the interface to use for packets here
export interface="`head -1 /tmp/interface`"

# select a random server IPv6 address, if the experiment requires it
export server="` \
    awk '/^ADDR server/ { print $NF }' /tmp/experiment/setup-data | \
    shuf | \
    head -1`"

# run any preparation which we do not want to measure; we only run the
# first one we find, but if that needs to include a more generic one it
# can do that
if [ -x "/tmp/experiment/prepare-$experiment-$type" ]
then
    "/tmp/experiment/prepare-$experiment-$type" "$server" "$interface"
elif [ -x "/tmp/experiment/prepare-$experiment" ]
then
    "/tmp/experiment/prepare-$experiment" "$server" "$interface"
elif [ -x "/tmp/experiment/prepare-$type" ]
then
    "/tmp/experiment/prepare-$type" "$server" "$interface"
elif [ -x "/tmp/experiment/prepare" ]
then
    "/tmp/experiment/prepare" "$server" "$interface"
fi

# run the scheduler for clients only
if [ "$type" = client ]
then
    "/tmp/experiment/schedule-$schedule"
    # make sure we don't find a permission problem because some experiments
    # run as root, and some don't
    sudo rm -f /tmp/datafile
fi

sed -e 's/\[TYPE\]/'"$type"'/g' \
    -e 's/\[NODE\]/'"$number"'/g' \
    -e 's/\[EXPERIMENT\]/'"$experiment"'/g' \
    -e 's/\[INTERFACE\]/'"$interface"'/g' \
    -e 's/\[SERVER\]/'"$server"'/g' \
    -e 's/\[SCHEDULE\]/'"$schedule"'/g' \
    -e 's/\[SIZE\]/'"$size"'/g' \
    /tmp/experiment/lwmon-config > /tmp/lwmon-config

export logfile="/tmp/logs/$type$number.$experiment.$schedule.$size"

ifnum=0
while read ifname
do
    ifnum=$(( 1 + $ifnum ))
    echo "network if$ifnum 1 $ifname" >> /tmp/lwmon-config
done < /tmp/interface

sudo rm -r /tmp/results /tmp/logs >/dev/null 2>&1
mkdir /tmp/results /tmp/logs
sudo rm /tmp/lwmon.socket >/dev/null 2>&1
lwmon -c /tmp/lwmon-config

# copy the results back to director -- which seems to be unable to cope
# with too many incoming connections, hence the loop and retries
director="`awk '/^ADDR director/ { print $NF; exit }' /tmp/experiment/setup-data`"
if [ -f "$logfile" ]
then
    for n in 1 2 3 4 5 6 7 8
    do
	rsync -aqH --partial --partial-dir .partial \
	    -e 'ssh -oCheckHostIP=no -oStrictHostKeyChecking=no -i/tmp/experiment/id_rsa' \
	    "$logfile" "[$director]:/tmp/logs/" && break
	sleep 1
    done
fi

for n in 1 2 3 4 5 6 7 8
do
    rsync -aqH --partial --partial-dir .partial \
	-e 'ssh -oCheckHostIP=no -oStrictHostKeyChecking=no -i/tmp/experiment/id_rsa' \
	--omit-dir-times /tmp/results/ "[$director]:/tmp/results/" && break
    sleep 1
done

#rm -r /tmp/results /tmp/logs >/dev/null 2>&1

