#!/bin/sh

# run iotupd until the end of the experiment

#sudo iotupd /tmp/datafile ff1e::42 "$1" >"$logfile" 2>&1 &
sudo iotupd /tmp/datafile ff1e::42 "$1" --mld >"$logfile" 2>&1 &
echo "$!" > /tmp/experiment.pid
wait

