#!/bin/sh

# start our own sshd on a different port so we can monitor it,
# and get easier connect/disconnect logs; unlike the other experiments,
# which write directly to the lwmon socket, here we use an unmodified
# sshd so we have to parse the output

(sleep 1; lwmon-log -n "$type$number" server_scp start) &
sudo /usr/sbin/sshd -D -e -p 7722 -o 'PidFile /tmp/sshd.pid' 2>&1 | \
while read line
do
    echo "$line" >> "$logfile"
    case "$line" in
	'Accepted publickey'*) lwmon-log -n "$type$number" server_scp request ;;
	'Received disconnect'*) lwmon-log -n "$type$number" server_scp done ;;
    esac
done
lwmon-log -n "$type$number" server_scp end

