#!/bin/sh

# run lcroute

sudo lcroute `tail -1 /tmp/interface` `head -1 /tmp/interface` >>"$logfile" 2>&1 &
echo "$!" > /tmp/experiment.pid
# give it time to set up
sleep 5
lwmon-log -n "$type$number" router_multicast start
wait
lwmon-log -n "$type$number" router_multicast end

