#!/bin/sh

# run pim6sd

sudo pim6sd -f /tmp/pim6sd.conf -n >>"$logfile" 2>&1 &
echo "$!" > /tmp/experiment.pid
# give it time to set up
sleep 5
lwmon-log -n "$type$number" router_multicast start
wait
lwmon-log -n "$type$number" router_multicast end

